### PR TITLE
chore(Build): Branch bump for new dist

### PR DESCRIPTION
**Pull request by tannermares**
## Why this was needed
It looks like the though the `src` was updated to handle dependabot PRs the `dist`was never compiled. It looks like we have an auto compile workflow but it only works on branches. So here's a new branch we can make a release off.

## How I did it
- git branch
- git push

### CODE REVIEW

**Comment by tannermares** [comment]
@molawson is this what I need to do? 😂

**Comment by molawson** [comment]
😂 From the looks of the [action](https://github.com/planningcenter/pull-assign-action/blob/main/.github/workflows/build.yml) (that was copy/pasted from other actions), it looks like you might need to make a change to `package.json` or someting in `src/`

**Comment by molawson** [comment]
@tannermares It's building! 

I'm really (clearly) not well-versed in how this build process works.  But it looks like the [build](https://github.com/planningcenter/pull-assign-action/blob/4622ba25a9daf31fd86046bfddf8fb76c1c01f45/dist/index.js#L9713) still has the old version of the conditional we're [looking for](https://github.com/planningcenter/pull-assign-action/blob/main/src/action.js#L21).

Maybe the build is being smart and we need to change something in `src/action.js` to get it to pick that up? 🤞🏼

**Comment by tannermares** [comment]
dang it still no dice...

**Review by molawson — APPROVED** [review]
Thanks for getting to the bottom of this!  I'm unreasonably excited to rid our PRs that unnecessary ❌ 😂 

I guess after merging, we can cut a new release and everyone will get the update 🤞🏼

**Comment by tannermares** [comment]
@molawson can we release a patch and anyone using 1.2 will pull it automatically? or release 1.3?

**Comment by molawson** [comment]
@tannermares I think this should be `v1.2.1`.  If you cut a new release with that tag, this [action](https://github.com/planningcenter/pull-assign-action/blob/main/.github/workflows/update-action-tags.yml) should move `v1` and `v1.2` to point to `v1.2.1`, so anyone using those less-specific versions will get the update without needing to make any changes.

**Comment by geolessel** [comment]
LGTM! 👍

**Pull request merged**
